import type { CommandCenterSnapshot } from "@/types/operational";

/**
 * Isolated synthetic snapshot for Phase 1.
 * Deterministic timestamps — do not use Date.now() here (SSR hydration).
 * NEVER present this as live industrial telemetry.
 */
export const DEMO_SNAPSHOT_AT = "2026-09-16T14:32:08+03:00";

export const DEMO_DISCLAIMER =
  "SYNTHETIC DEMO DATA — not live plant telemetry. Backend remains authoritative when connected.";

const spark = (start: number, noise: number[]): number[] =>
  noise.reduce<number[]>((acc, n) => {
    acc.push(Number((acc[acc.length - 1]! + n).toFixed(2)));
    return acc;
  }, [start]);

const series = (start: string, values: number[]): { t: string; v: number }[] =>
  values.map((v, i) => {
    const t = new Date(Date.parse(start) - (values.length - 1 - i) * 60_000);
    return { t: t.toISOString(), v };
  });

export const commandCenterDemo: CommandCenterSnapshot = {
  meta: {
    source: "demo",
    snapshotAt: DEMO_SNAPSHOT_AT,
    organization: {
      id: "org_east_africa_mfg",
      name: "East Africa Manufacturing Group",
      code: "EAMG",
    },
    plant: {
      id: "plant_01",
      organizationId: "org_east_africa_mfg",
      name: "Plant 01 — Athi River",
      code: "P-01",
      timezone: "Africa/Nairobi",
    },
    shift: {
      id: "shift_b",
      name: "Shift B",
      startedAt: "2026-09-16T14:00:00+03:00",
      endsAt: "2026-09-16T22:00:00+03:00",
    },
    connectivity: "live",
    disclaimer: DEMO_DISCLAIMER,
  },
  health: {
    status: "warning",
    summary:
      "Plant is producing below target. Line 02 is the binding constraint. Electrical demand is within contracted load.",
  },
  kpis: [
    {
      id: "oee",
      label: "Plant OEE",
      value: 84.2,
      unit: "%",
      precision: 1,
      target: 85.0,
      delta: -0.8,
      deltaUnit: "pp",
      timeContext: "Rolling 8h",
      status: "warning",
      domain: "production",
      hierarchy: "primary",
      diagnostics: [
        { label: "Availability", value: "92.4%" },
        { label: "Performance", value: "94.1%" },
        { label: "Quality", value: "96.8%" },
      ],
      sparkline: spark(85.1, [-0.2, 0.1, -0.3, -0.1, 0.2, -0.4, -0.2, 0.0, -0.1, -0.1]),
      source: "demo",
      observedAt: DEMO_SNAPSHOT_AT,
    },
    {
      id: "throughput",
      label: "Throughput",
      value: 1284,
      unit: "pcs/h",
      precision: 0,
      target: 1420,
      delta: -136,
      deltaUnit: "pcs/h",
      timeContext: "Last 60 min",
      status: "warning",
      domain: "production",
      hierarchy: "primary",
      sparkline: spark(1410, [-8, -12, 4, -20, -6, -10, 2, -18, -4, -14]),
      source: "demo",
      observedAt: DEMO_SNAPSHOT_AT,
    },
    {
      id: "demand",
      label: "Electrical demand",
      value: 4.86,
      unit: "MW",
      precision: 2,
      target: 5.4,
      delta: 0.12,
      deltaUnit: "MW",
      timeContext: "Instantaneous",
      status: "normal",
      domain: "energy",
      hierarchy: "primary",
      sparkline: spark(4.62, [0.04, 0.02, 0.06, -0.01, 0.03, 0.05, 0.01, 0.02, 0.01, 0.01]),
      source: "demo",
      observedAt: DEMO_SNAPSHOT_AT,
    },
    {
      id: "inventory",
      label: "Inventory buffers",
      value: 6.4,
      unit: "h",
      precision: 1,
      target: 8.0,
      delta: -0.6,
      deltaUnit: "h",
      timeContext: "WIP + FG cover",
      status: "warning",
      domain: "inventory",
      hierarchy: "secondary",
      sparkline: spark(7.2, [-0.1, 0, -0.1, -0.2, 0, -0.1, -0.1, 0, -0.1, -0.1]),
      source: "demo",
      observedAt: DEMO_SNAPSHOT_AT,
    },
    {
      id: "docks",
      label: "Dock utilization",
      value: 71.0,
      unit: "%",
      precision: 0,
      target: 75.0,
      delta: 4.0,
      deltaUnit: "pp",
      timeContext: "Current hour",
      status: "normal",
      domain: "logistics",
      hierarchy: "secondary",
      sparkline: spark(62, [2, 1, 3, -1, 2, 1, 0, 2, 1, 0]),
      source: "demo",
      observedAt: DEMO_SNAPSHOT_AT,
    },
  ],
  bottleneck: {
    id: "bn_line_02",
    location: "Line 02 Assembly",
    process: "Final assembly",
    kind: "Capacity constraint",
    why: "Machine M-204 cycle time increased after the 13:40 changeover. Downstream starve is visible on Line 03.",
    severity: "warning",
    currentRate: 280,
    targetRate: 340,
    rateUnit: "pcs/h",
    constraintAsset: "M-204",
    utilizationPct: 97.4,
    economicImpactPerHour: null,
    economicImpactNote: "Economic impact is not computed in the demo layer. Backend optimization owns this value.",
    capacityNote: "Nameplate 360 pcs/h · demonstrated 340 pcs/h",
    recommendation: "Open scenario LAB-014 against a 12-minute changeover reduction on M-204.",
  },
  optimization: {
    modelId: "OPT-014",
    modelVersion: "2.4.1",
    scenarioId: "SCN-BASE-SHIFT-B",
    objective: "Maximize throughput subject to energy contract and labor roster",
    solver: "HiGHS 1.7",
    status: "optimal",
    solveTimeMs: 1840,
    optimalityGapPct: 0.0,
    bindingConstraints: ["Line 02 capacity (M-204)", "Shift B skilled labor"],
    baselineLabel: "Current dispatch",
    expectedImpact: "+4.8% throughput if Line 02 changeover is recovered; energy within contract.",
    decisionVariablesNote: "Hold Line 01 mix. Do not pull Line 03 ahead of Line 02 recovery.",
  },
  alerts: [
    {
      id: "al_204",
      priority: "P2",
      title: "M-204 cycle time above threshold",
      summary: "Mean cycle 12.8s vs 10.6s demonstrated. Line 02 is binding.",
      source: "Asset telemetry",
      asset: "M-204",
      process: "Line 02 Assembly",
      observedAt: "2026-09-16T14:28:41+03:00",
      acknowledged: false,
    },
    {
      id: "al_buf",
      priority: "P2",
      title: "WIP buffer on Line 03 below 45 min",
      summary: "Starvation risk if Line 02 does not recover within 25 minutes.",
      source: "Inventory",
      asset: "BUF-L03",
      process: "Line 03",
      observedAt: "2026-09-16T14:30:02+03:00",
      acknowledged: false,
    },
    {
      id: "al_q",
      priority: "P3",
      title: "First-pass yield drift on SKU-441",
      summary: "FPY 96.1% over last 90 minutes versus 97.4% shift baseline.",
      source: "Quality",
      asset: "INSP-12",
      process: "Line 01",
      observedAt: "2026-09-16T14:18:11+03:00",
      acknowledged: true,
    },
    {
      id: "al_info",
      priority: "P4",
      title: "Shift B roster confirmed",
      summary: "14 of 14 skilled stations filled. No labor constraint on Line 01.",
      source: "Workforce",
      asset: "—",
      process: "Plant 01",
      observedAt: "2026-09-16T13:58:00+03:00",
      acknowledged: true,
    },
  ],
  telemetry: [
    {
      id: "prod_rate",
      label: "Plant throughput",
      unit: "pcs/h",
      domain: "production",
      current: 1284,
      threshold: { label: "Target", value: 1420 },
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      points: series(DEMO_SNAPSHOT_AT, [1410, 1398, 1380, 1362, 1350, 1331, 1324, 1308, 1296, 1284]),
    },
    {
      id: "kw",
      label: "Electrical demand",
      unit: "MW",
      domain: "energy",
      current: 4.86,
      threshold: { label: "Contract", value: 5.4 },
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      points: series(DEMO_SNAPSHOT_AT, [4.62, 4.66, 4.68, 4.74, 4.73, 4.76, 4.81, 4.82, 4.84, 4.86]),
    },
    {
      id: "dock",
      label: "Dock occupancy",
      unit: "%",
      domain: "logistics",
      current: 71,
      threshold: { label: "Plan", value: 75 },
      freshness: "updated",
      observedAt: "2026-09-16T14:31:40+03:00",
      points: series(DEMO_SNAPSHOT_AT, [62, 64, 65, 68, 67, 69, 70, 69, 71, 71]),
    },
  ],
  attention: [
    {
      id: "att_1",
      title: "Recover M-204 changeover",
      detail: "Primary bottleneck. Open scenario vs 12-minute reduction.",
      status: "warning",
      href: "/optimization",
    },
    {
      id: "att_2",
      title: "Protect Line 03 WIP",
      detail: "Buffer cover 38 min. Do not pull additional mix onto Line 03.",
      status: "warning",
      href: "/inventory",
    },
    {
      id: "att_3",
      title: "SKU-441 FPY watch",
      detail: "Advisory only. Quality owns inspection plan INSP-12.",
      status: "normal",
      href: "/quality",
    },
  ],
  intelligence: [
    {
      kind: "system-fact",
      title: "System fact",
      body: "Line 03 throughput declined 14% over the last 42 minutes. Line 02 is at 97.4% utilization on M-204.",
    },
    {
      kind: "optimization-result",
      title: "Optimization result",
      body: "Model OPT-014 identifies Line 02 capacity as a binding constraint. Solver status: optimal. Gap 0.0%.",
    },
    {
      kind: "ai-interpretation",
      title: "AI interpretation",
      body: "Possible contributing factor: increased changeover duration on M-204 after 13:40. This is not a control action.",
    },
    {
      kind: "human-decision",
      title: "Human decision",
      body: "Review the scenario, approve a recovery plan, or dismiss. AI cannot dispatch the plant.",
    },
  ],
};
