import type { PlantTopologySnapshot } from "@/types/topology";
import { DEMO_DISCLAIMER, DEMO_SNAPSHOT_AT, commandCenterDemo } from "./command-center";

/**
 * Isolated Plant Overview topology.
 * Nodes and flows are derived only from Command Center demo entities.
 * Do not treat this as a second source of operational truth.
 */
const cc = commandCenterDemo;
const bn = cc.bottleneck!;

export const plantTopologyDemo: PlantTopologySnapshot = {
  meta: {
    ...cc.meta,
    disclaimer: DEMO_DISCLAIMER,
  },
  health: cc.health,
  counts: {
    areas: 1,
    lines: 3,
    machines: 1,
    constraints: 1,
  },
  sequence: ["line_01", "line_02", "line_03", "docks"],
  nodes: [
    {
      id: "line_01",
      name: "Line 01",
      kind: "line",
      kindLabel: "Production line",
      status: "normal",
      statusNote: "Shift B skilled stations filled. SKU-441 FPY is an acknowledged advisory.",
      utilizationPct: null,
      capacityNote: null,
      constraintId: null,
      constraintLabel: null,
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      metrics: [
        { label: "Labor", value: "14 / 14 stations" },
        { label: "Quality", value: "SKU-441 FPY 96.1% (P3 ack.)" },
      ],
      actions: [
        { label: "View production", href: "/production", enabled: true },
        { label: "View quality", href: "/quality", enabled: true },
      ],
    },
    {
      id: "line_02",
      name: bn.location,
      kind: "line",
      kindLabel: "Production line",
      status: bn.severity,
      statusNote: bn.kind,
      utilizationPct: bn.utilizationPct,
      capacityNote: bn.capacityNote,
      constraintId: "m_204",
      constraintLabel: bn.constraintAsset,
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      metrics: [
        { label: "Current", value: `${bn.currentRate} ${bn.rateUnit}` },
        { label: "Target", value: `${bn.targetRate} ${bn.rateUnit}` },
        { label: "Utilization", value: `${bn.utilizationPct}%` },
      ],
      actions: [
        { label: "View production", href: "/production", enabled: true },
        { label: "Analyze constraint", href: "/analytics", enabled: true },
        { label: "View asset", href: "/assets/M-204", enabled: true },
      ],
    },
    {
      id: "m_204",
      name: bn.constraintAsset,
      kind: "machine",
      kindLabel: "Machine",
      status: "warning",
      statusNote: "Cycle time above threshold",
      utilizationPct: bn.utilizationPct,
      capacityNote: "Demonstrated 10.6 s · observed 12.8 s",
      constraintId: "m_204",
      constraintLabel: bn.kind,
      freshness: "updated",
      observedAt: "2026-09-16T14:28:41+03:00",
      metrics: [
        { label: "Mean cycle", value: "12.8 s" },
        { label: "Demonstrated", value: "10.6 s" },
        { label: "Changeover", value: "13:40" },
      ],
      actions: [
        { label: "View asset", href: "/assets/M-204", enabled: true },
        { label: "Analyze constraint", href: "/analytics", enabled: true },
        {
          label: "Dispatch recovery",
          href: "/optimization",
          enabled: false,
          reason: "Backend authorization required",
        },
      ],
    },
    {
      id: "line_03",
      name: "Line 03",
      kind: "line",
      kindLabel: "Production line",
      status: "warning",
      statusNote: "Downstream starve from Line 02. Throughput declined 14% over 42 minutes.",
      utilizationPct: null,
      capacityNote: null,
      constraintId: "line_02",
      constraintLabel: "Line 02",
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      metrics: [
        { label: "Throughput", value: "−14% / 42 min" },
        { label: "WIP cover", value: "38 min" },
      ],
      actions: [
        { label: "View production", href: "/production", enabled: true },
        { label: "View inventory", href: "/inventory", enabled: true },
      ],
    },
    {
      id: "buf_l03",
      name: "BUF-L03",
      kind: "buffer",
      kindLabel: "Inventory buffer",
      status: "warning",
      statusNote: "WIP buffer on Line 03 below 45 min.",
      utilizationPct: null,
      capacityNote: "Cover 38 min",
      constraintId: "line_02",
      constraintLabel: "Starved by Line 02",
      freshness: "updated",
      observedAt: "2026-09-16T14:30:02+03:00",
      metrics: [
        { label: "Cover", value: "38 min" },
        { label: "Threshold", value: "45 min" },
      ],
      actions: [{ label: "View inventory", href: "/inventory", enabled: true }],
    },
    {
      id: "docks",
      name: "Docks",
      kind: "logistics",
      kindLabel: "Logistics interface",
      status: "normal",
      statusNote: "Dock occupancy within plan band.",
      utilizationPct: 71,
      capacityNote: "Plan 75%",
      constraintId: null,
      constraintLabel: null,
      freshness: "updated",
      observedAt: "2026-09-16T14:31:40+03:00",
      metrics: [
        { label: "Occupancy", value: "71%" },
        { label: "Plan", value: "75%" },
      ],
      actions: [{ label: "View logistics", href: "/logistics", enabled: true }],
    },
    {
      id: "energy",
      name: "Electrical demand",
      kind: "energy",
      kindLabel: "Energy interface",
      status: "normal",
      statusNote: "Instantaneous demand within contracted load.",
      utilizationPct: null,
      capacityNote: "Contract 5.4 MW",
      constraintId: null,
      constraintLabel: null,
      freshness: "updated",
      observedAt: DEMO_SNAPSHOT_AT,
      metrics: [
        { label: "Demand", value: "4.86 MW" },
        { label: "Contract", value: "5.4 MW" },
      ],
      actions: [{ label: "View energy", href: "/energy", enabled: true }],
    },
  ],
  edges: [
    {
      id: "e_l1_l2",
      from: "line_01",
      to: "line_02",
      flow: "production",
      label: "Production",
      constrained: false,
    },
    {
      id: "e_l2_m204",
      from: "line_02",
      to: "m_204",
      flow: "production",
      label: "Constraint",
      constrained: true,
    },
    {
      id: "e_l2_l3",
      from: "line_02",
      to: "line_03",
      flow: "production",
      label: "Production",
      constrained: true,
    },
    {
      id: "e_l3_buf",
      from: "line_03",
      to: "buf_l03",
      flow: "material",
      label: "WIP buffer",
      constrained: true,
    },
    {
      id: "e_l3_docks",
      from: "line_03",
      to: "docks",
      flow: "material",
      label: "Finished goods",
      constrained: false,
    },
    {
      id: "e_energy_l2",
      from: "energy",
      to: "line_02",
      flow: "energy",
      label: "Within contract",
      constrained: false,
    },
  ],
  bottleneck: bn,
  impact: [
    {
      id: "imp_cap",
      label: "Capacity reduced",
      detail: `Line 02 ${bn.currentRate} ${bn.rateUnit} versus target ${bn.targetRate}.`,
      status: "warning",
    },
    {
      id: "imp_thr",
      label: "Throughput affected",
      detail: "Plant throughput 1,284 pcs/h versus target 1,420 pcs/h.",
      status: "warning",
    },
    {
      id: "imp_buf",
      label: "Downstream buffer affected",
      detail: "BUF-L03 cover 38 min. Line 03 starvation risk if Line 02 does not recover.",
      status: "warning",
    },
    {
      id: "imp_econ",
      label: "Economic impact",
      detail: bn.economicImpactNote,
      status: "normal",
    },
  ],
  alerts: cc.alerts,
  intelligence: cc.intelligence.filter(
    (block) =>
      block.kind === "optimization-result" || block.kind === "ai-interpretation",
  ),
};
